import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {

  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {
            data.map((info) => (
                <Link href={`/events/` + info.id} key={info.id}>
                <h2>{info.title}</h2>
                <p>{info.description}</p>
                <Image width={200} height={200} src={info.image} alt={info.id}/>
                </Link>
            ))
          }
        </div>
      </main>
    </>
  )
}

// prerender data from the server side
export async function getServerSideProps () {
  const {events_categories}= await import("../data/data.json")
  return {
      props: {
          data: events_categories
      }
  }
}